#ifndef BELLWIN_VERSION_H
#define BELLWIN_VERSION_H

#define VER_MAJOR 1
#define VER_MINOR 0
#define VER_PATCH 9
#define VER_BUILD 0

#define VER_FILEVERSION VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD
#define VER_FILEVERSION_STR "1.0.9.0"
#define VER_PRODUCTVERSION VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD
#define VER_PRODUCTVERSION_STR "1.0.9.0"

#endif
